## server
server:
  port: 18888
spring:
  application:
    name: fb-cms
  ## 数据库配置
  datasource:
    #Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    #type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fd_cms?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: foxbank
    password: Foxbank!123
    hikari.minimum-idle: 5
    hikari.idle-timeout: 180000
    hikari.maximum-pool-size: 10
    hikari.auto-commit: true
    hikari.pool-name: FbAccountHikariCP
    hikari.max-lifetime: 1800000
    hikari.connection-timeout: 30000
    hikari.connection-test-query: SELECT 1